name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: go mod download

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        binary_name="instapaper-cli"
        if [ "$GOOS" = "windows" ]; then
          binary_name="${binary_name}.exe"
        fi

        output_name="${binary_name}-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          output_name="${output_name}.exe"
        fi

        # Get version info
        VERSION=$(git describe --tags --abbrev=0 --match=v* 2>/dev/null || echo "v0.0.0")
        COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        # Build with version info embedded
        go build -ldflags="-s -w -X 'instapaper-cli/internal/version.Version=${VERSION}' -X 'instapaper-cli/internal/version.Commit=${COMMIT}' -X 'instapaper-cli/internal/version.Date=${DATE}'" -o "$output_name" cmd/instapaper-cli/main.go

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.goos }}-${{ matrix.goarch }}
        path: instapaper-cli-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: binary-*
        merge-multiple: true

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: instapaper-cli-*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}